### ISSUE TITLE
General Roadmap

### ISSUE THREAD

**Issue by pkos98** [pkos98/discuss#1]
## Feature roadmap  
- [x] Add ability to **comment** on topics #2
  - [x] *Optional* Make commenting *real-time* (live loading of newly added comments without having to refresh the page)
- [x] Implement a form of **authentication** #3 
  - [x] *Optional* Use OAuth for authentication

**Comment by pkos98** [comment]
Finished
